library(future)
library(furrr)
library(tictoc)
library(tidyverse)
source("dad_bot.R")


# function to build model and generate texts
test_params <- function(input_text, markov_state_size,
                        max_overlap_ratio, maximum_sentence_length,
                        return_texts=FALSE) {

  model <- create_model(
    input_text=input_text,
    markov_state_size=markov_state_size,
    max_overlap_ratio=max_overlap_ratio
  )

  texts <- generate_texts(
    markov_model=model,
    maximum_sentence_length=maximum_sentence_length
  )

  if (return_texts) return(texts)

  return(list(
    "markov_state_size" = markov_state_size,
    "max_overlap_ratio" = max_overlap_ratio,
    "maximum_sentence_length" = maximum_sentence_length,
    "num" = length(texts)
    )
  )
}


# specify params to test (expand.grid creates all possible combos)
params <- expand.grid(
  list(
    "markov_state_size" = 1:5,
    "max_overlap_ratio" = seq(0, 1, by=0.15),
    "maximum_sentence_length" = seq(1, 100, by=10)
    )
  )


# process in parallel since there are so many combinations to test
# be warned: this takes a long time :-)
plan(future::multisession, workers = floor(availableCores() / 2))

tic()

result <- furrr::future_pmap_dfr(
  params,
  test_params,
  input_text=text_data,
  .options=furrr_options(seed = TRUE),
  .progress=TRUE
)

toc()

# look at the distribution of number of sentences generated by each combo

# markov_state_size: big dropoff after 2. limit to 1-2
result %>%
  group_by(markov_state_size) %>%
  summarize(avg_n = mean(num), med_n = median(num), total_n = sum(num))

# max_overlap_ratio: limit to 0.25-1
result %>%
  group_by(max_overlap_ratio) %>%
  summarize(avg_n = mean(num), med_n = median(num), total_n = sum(num))

# maximum_sentence_length: anything > 20 is probably okay
result %>%
  group_by(msl) %>%
  summarize(avg_n = mean(num), med_n = median(num), total_n = sum(num))





# TODO: clean this up -- rerunning with fewer params to generate the data for the app
# specify params to test (expand.grid creates all possible combos)
params <- expand.grid(
  list(
    "markov_state_size" = 1:2,
    "max_overlap_ratio" = seq(0.2, 0.8, by=0.2),
    "maximum_sentence_length" = seq(20, 100, by=20)
  )
)


# process in parallel since there are so many combinations to test
# be warned: this takes a long time :-)
plan(future::multisession, workers = floor(availableCores() / 2))

tic()

result <- furrr::future_pmap(
  params,
  test_params,
  input_text=text_data,
  return_texts=TRUE,
  .options=furrr_options(seed = TRUE),
  .progress=TRUE
)

toc()

saveRDS(params, file="data/inputs.RDS")
saveRDS(result, file="data/generated_texts.RDS")
